TheExampleApp/Models/Course.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Contentful.Core.Models;

namespace TheExampleApp.Models
{
    /// <summary>
    /// Represents
    /// </summary>
    public class Course
    {
        /// <summary>
        /// The system defined meta data properties.
        /// </summary>
        public SystemProperties Sys { get; set; }

        /// <summary>
        /// The title of the course.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// The slug for the course.
        /// </summary>
        public string Slug { get; set; }

        /// <summary>
        /// The image for the course.
        /// </summary>
        public Asset Image { get; set; }

        /// <summary>
        /// The short description of the course.
        /// </summary>
        public string ShortDescription { get; set; }

        /// <summary>
        /// The description of the course.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// The duration of the course in minutes.
        /// </summary>
        public int Duration { get; set; }

        /// <summary>
        /// The skill level required to complete the course.
        /// </summary>
        public string SkillLevel { get; set; }

        /// <summary>
        /// The lessons this course contain.
        /// </summary>
        public List<Lesson> Lessons { get; set; }

        /// <summary>
        /// The categories this course belongs to.
        /// </summary>
        public List<Category> Categories { get; set; }
    }
}

TheExampleApp/Pages/Courses.cshtml.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Contentful.Core;
using Contentful.Core.Search;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheExampleApp.Configuration;
using TheExampleApp.Models;

namespace TheExampleApp.Pages
{
    /// <summary>
    /// Model for the /courses view.
    /// </summary>
    public class CoursesModel : BasePageModel
    {
        private readonly IBreadcrumbsManager _breadcrumbsManager;
        private readonly IViewLocalizer _localizer;

        /// <summary>
        /// Instantiates the model.
        /// </summary>
        /// <param name="client">The client used to communicate with the Contentful API.</param>
        /// <param name="breadcrumbsManager">Class that manages which breadcrumbs the view should display.</param>
        public CoursesModel(IContentfulClient client, IBreadcrumbsManager breadcrumbsManager, IViewLocalizer localizer) : base(client)
        {
            _breadcrumbsManager = breadcrumbsManager;
            _localizer = localizer;
        }

        /// <summary>
        /// Returns the result of getting the view.
        /// </summary>
        /// <param name="category">The optional category to filter courses by.</param>
        /// <returns>The view.</returns>
        public async Task<IActionResult> OnGet(string category)
        {
            // Get all categories since they're always displayed in the left hand side of the view.
            var categories = await _client.GetEntriesByType("category", QueryBuilder<Category>.New.Include(5).LocaleIs(HttpContext?.Session?.GetString(Startup.LOCALE_KEY) ?? CultureInfo.CurrentCulture.ToString()));
            var queryBuilder = QueryBuilder<Course>.New.ContentTypeIs("course").Include(5).LocaleIs(HttpContext?.Session?.GetString(Startup.LOCALE_KEY) ?? CultureInfo.CurrentCulture.ToString()).OrderBy("-sys.createdAt");

            var courses = await _client.GetEntries(queryBuilder);

            Categories = categories.ToList();
            SelectedCategory = categories.FirstOrDefault(c => c.Slug == category);

            if (!string.IsNullOrEmpty(category))
            {
                // Filter the courses by the selected category.
                Courses = courses.Where(c => c.Categories != null && c.Categories.Any(x => x.Slug == category.ToLower())).ToList();
                var cat = Categories.FirstOrDefault(c => c.Slug == category.ToLower());

                if(cat == null)
                {
                    TempData["NotFound"] = _localizer["errorMessage404Category"].Value;
                    return NotFound();
                }
                // Replace the breadcrumb for the category to the title of the category, which is more readable.
                _breadcrumbsManager.ReplaceCrumbForSlug(category.ToLower().Replace('-', ' '), cat.Title);
            }
            else
            {
                // If we don't have a category, just display all courses.
                Courses = courses.ToList();
            }
            return Page();
        }

        /// <summary>
        /// The currently selected category.
        /// </summary>
        public Category SelectedCategory { get; set; }

        /// <summary>
        /// The courses to display.
        /// </summary>
        public List<Course> Courses { get; set; }

        /// <summary>
        /// The categories to display.
        /// </summary>
        public List<Category> Categories { get; set; }

        /// <summary>
        /// Returns wether or not editorial features are enabled.
        /// </summary>
        public bool EditorialFeaturesEnabled => HttpContext.Session.GetString("EditorialFeatures") == "Enabled";
    }
}

TheExampleApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Contentful.Core.Errors;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TheExampleApp.Pages
{
    /// <summary>
    /// Model for the error view.
    /// </summary>
    public class ErrorModel : PageModel
    {
        /// <summary>
        /// The request id of the request that had an error.
        /// </summary>
        public string RequestId { get; set; }

        /// <summary>
        /// Whether or not to display the request id.
        /// </summary>
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        /// <summary>
        /// The ContentfulException, if any, that occurred.
        /// </summary>
        public ContentfulException ContentfulException { get; set; }

        /// <summary>
        /// Displays the error view.
        /// </summary>
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;

            // Get the last exception that occurred.
            var ex = HttpContext?.Features?.Get<IExceptionHandlerFeature>()?.Error;

            if(ex is ContentfulException)
            {
                ContentfulException = ex as ContentfulException;
                RequestId = ContentfulException.RequestId;
            }
        }
    }
}

TheExampleApp/Pages/Imprint.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TheExampleApp.Pages
{
    /// <summary>
    /// Model for the /imprint view.
    /// </summary>
    /// <remarks>Very uninteresting class.</remarks>
    public class ImprintModel : PageModel
    {
        /// <summary>
        /// Returns the view.
        /// </summary>
        public void OnGet()
        {

        }
    }
}

TheExampleApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Contentful.Core;
using Contentful.Core.Models;
using Contentful.Core.Search;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheExampleApp.Models;

namespace TheExampleApp.Pages
{
    /// <summary>
    /// Model for the index view.
    /// </summary>
    public class IndexModel : BasePageModel
    {
        /// <summary>
        /// Instantiates the model.
        /// </summary>
        /// <param name="client">The client used to communicate with the Contentful API.</param>
        public IndexModel(IContentfulClient client) : base(client)
        {
        }

        /// <summary>
        /// Returns the result of getting the view.
        /// </summary>
        /// <returns>The view.</returns>
        public async Task OnGet()
        {
            var queryBuilder = QueryBuilder<Layout>.New.ContentTypeIs("layout").FieldEquals(f => f.Slug, "home").Include(4).LocaleIs(HttpContext?.Session?.GetString(Startup.LOCALE_KEY) ?? CultureInfo.CurrentCulture.ToString());
            var indexPage = (await _client.GetEntries(queryBuilder)).FirstOrDefault();
            IndexPage = indexPage;
            var systemProperties = new List<SystemProperties> { indexPage.Sys };
            if (indexPage.ContentModules != null && indexPage.ContentModules.Any())
            {
                systemProperties.AddRange(indexPage.ContentModules?.Select(c => c.Sys));
            }
            SystemProperties = systemProperties;
        }

        /// <summary>
        /// The layout to display.
        /// </summary>
        public Layout IndexPage { get; set; }

        /// <summary>
        /// All system properties this layout relies on.
        /// </summary>
        public IEnumerable<SystemProperties> SystemProperties { get; set; }
    }
}

TheExampleApp/ViewComponents/EditorialFeaturesViewComponent.cs
using Contentful.Core;
using Contentful.Core.Configuration;
using Contentful.Core.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TheExampleApp.Configuration;

namespace TheExampleApp.ViewComponents
{
    /// <summary>
    /// Viev component handling whether or not to display editorial features.
    /// </summary>
    public class EditorialFeaturesViewComponent : ViewComponent
    {
        private readonly ContentfulOptions _options;

        /// <summary>
        /// Instantiates the view component.
        /// </summary>
        /// <param name="optionsManager">The class that manages the Contentful configuration for the application.</param>
        public EditorialFeaturesViewComponent(IContentfulOptionsManager optionsManager)
        {
            _options = optionsManager.Options;
        }

        /// <summary>
        /// Invokes the view component and returns the result.
        /// </summary>
        /// <param name="sys">They system properties of the entry to display editorial features for.</param>
        /// <returns>The view.</returns>
        public IViewComponentResult Invoke(IEnumerable<SystemProperties> sys)
        {
            var model = new EditorialFeaturesModel();
            model.Sys = sys;
            model.FeaturesEnabled = HttpContext.Session.GetString("EditorialFeatures") == "Enabled";
            model.SpaceId = _options.SpaceId;
            model.UsePreviewApi = _options.UsePreviewApi;

            return View(model);
        }
    }

    /// <summary>
    /// Model for the <see cref="EditorialFeaturesViewComponent"/> view.
    /// </summary>
    public class EditorialFeaturesModel
    {
        /// <summary>
        /// The system properties of the entry to display editorial features for.
        /// </summary>
        public IEnumerable<SystemProperties> Sys { get; set; }
        /// <summary>
        /// Whether or not features should be enabled.
        /// </summary>
        public bool FeaturesEnabled { get; set; }
        /// <summary>
        /// Whether or not the preview API should be used.
        /// </summary>
        public bool UsePreviewApi { get; set; }
        /// <summary>
        /// The current space id.
        /// </summary>
        public string SpaceId { get; set; }
    }
}

TheExampleApp/ViewComponents/LocalesViewComponent.cs
using Contentful.Core;
using Contentful.Core.Models;
using Contentful.Core.Models.Management;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace TheExampleApp.ViewComponents
{
    /// <summary>
    /// View component handling the dropdown to change locale.
    /// </summary>
    public class LocalesViewComponent : ViewComponent
    {
        private readonly IContentfulClient _client;

        /// <summary>
        /// Instantiates the view component.
        /// </summary>
        /// <param name="client">The client used to communicate with the Contentful API.</param>
        public LocalesViewComponent(IContentfulClient client)
        {
            _client = client;
        }

        /// <summary>
        /// Invokes the view component and returns the result.
        /// </summary>
        /// <returns>The view.</returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            Space space = null;

            try
            {
                // Try to get the space, if this fails we're probably in a state of bad credentials.
                space = await _client.GetSpace();
            }
            catch
            {
                // Getting the space failed, set some default values.
                space = new Space() {
                    Locales = new List<Locale>()
                    {
                        new Locale
                        {
                            Code = "en-US",
                            Default = true,
                            Name = "U.S. English"
                        }
                    }
                };
            }
            var selectedLocale = HttpContext.Session.GetString(Startup.LOCALE_KEY) ?? CultureInfo.CurrentCulture.ToString();
            var localeInfo = new LocalesInfo
            {
                Locales = space.Locales,
                SelectedLocale = space?.Locales.FirstOrDefault(c => c.Code == selectedLocale) ?? space?.Locales.Single(c => c.Default),
            };

            HttpContext.Session.SetString(Startup.LOCALE_KEY, localeInfo.SelectedLocale?.Code);

            localeInfo.UsePreviewApi = _client.IsPreviewClient;

            return View(localeInfo);
        }
    }

    /// <summary>
    /// Model for the <see cref="LocalesViewComponent"/> view.
    /// </summary>
    public class LocalesInfo
    {
        /// <summary>
        /// The available locales.
        /// </summary>
        public List<Locale> Locales { get; set; }

        /// <summary>
        /// The currently selected locale.
        /// </summary>
        public Locale SelectedLocale { get; set; }

        /// <summary>
        /// Whether or no the Preview API is being used.
        /// </summary>
        public bool UsePreviewApi { get; set; }
    }
}

TheExampleApp/ViewComponents/MetaTagsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TheExampleApp.ViewComponents
{
    /// <summary>
    /// View component for the head meta tags.
    /// </summary>
    public class MetaTagsViewComponent : ViewComponent
    {
        private readonly IViewLocalizer _localizer;

        /// <summary>
        /// Initializes the view component.
        /// </summary>
        /// <param name="localizer">The localizer to localize the title with.</param>
        public MetaTagsViewComponent(IViewLocalizer localizer)
        {
            _localizer = localizer;
        }

        /// <summary>
        /// Invokes the view component and returns the view.
        /// </summary>
        /// <param name="title">The optional title to set for the current page.</param>
        /// <returns>The view.</returns>
        public IViewComponentResult Invoke(string title)
        {
            if (string.IsNullOrEmpty(title))
            {
                return View("Default", _localizer["defaultTitle"].Value);
            }

            return View("Default", $"{title} — {_localizer["defaultTitle"].Value}");
        }
    }
}

TheExampleApp/ViewComponents/SelectedApiViewComponent.cs
using Contentful.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TheExampleApp.ViewComponents
{
    /// <summary>
    /// View component for the API selector dropdown.
    /// </summary>
    public class SelectedApiViewComponent : ViewComponent
    {
        private readonly IContentfulClient _client;

        /// <summary>
        /// Instantiates the view component.
        /// </summary>
        /// <param name="client">The client used to communicate with the Contentful API.</param>
        public SelectedApiViewComponent(IContentfulClient client)
        {
            _client = client;
        }

        /// <summary>
        /// Invokes the view component and returns the result.
        /// </summary>
        /// <param name="currentPath">The path of the current request. Used to redirect the request back after changing the api.</param>
        /// <returns></returns>
        public IViewComponentResult Invoke(string currentPath)
        {
            return View(Tuple.Create(_client.IsPreviewClient, currentPath));
        }
    }
}

TheExampleApp/Pages/Courses.cshtml
@page
@model TheExampleApp.Pages.CoursesModel
@{
    ViewData["Title"] = $"{Localizer["allCoursesLabel"].Value} ({Model.Courses?.Count})";
}
<div class="layout-no-sidebar">@Html.Partial("Breadcrumbs")</div>
<div class="layout-sidebar">
    <section class="layout-sidebar__sidebar">
        <div class="layout-sidebar__sidebar-header">
            <h2 class="layout-sidebar__sidebar-title">@Localizer["categoriesLabel"]</h2>
        </div>
        <div class="layout-sidebar__sidebar-content">
            <div class="sidebar-menu">
                <ul class="sidebar-menu__list">
                    <li class="sidebar-menu__item">
                        <a class="sidebar-menu__link @(Model.SelectedCategory == null ? "active" : "")" href="/courses">@Localizer["allCoursesLabel"]</a>
                    </li>
                    @if (Model.Categories != null && Model.Categories.Any())
                    {
                        @foreach (var category in Model.Categories)
                        {
                            <li class="sidebar-menu__item">
                                <a class="sidebar-menu__link @(Model.SelectedCategory?.Slug == category.Slug ? "active" : "")"  href="/courses/categories/@category.Slug">@category.Title</a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </section>
    <section class="layout-sidebar__content">
        <div class="courses">
            <h1>@(Model.SelectedCategory != null ? Model.SelectedCategory.Title : Localizer["allCoursesLabel"].Value) (@Model.Courses?.Count)</h1>
            @if (Model.EditorialFeaturesEnabled)
            {
                <div class="editorial-features">
                    <div class="editorial-features__item">
                        <a class="editorial-features__text" target="_blank" rel="noopener" href="@($"https://app.contentful.com/spaces/{Model.Categories.FirstOrDefault()?.Sys?.Space?.SystemProperties?.Id}/entries/?contentTypeId=course")">
                            @Localizer["editInTheWebAppLabel"]
                        </a>
                        <div class="editorial-features__hint-wrapper">
                            <svg class="editorial-features__hint-icon">
                                <use xlink:href="/icons/icons.svg#info"></use>
                                <div class="editorial-features__hint-message">
                                    @Localizer["editorialFeaturesHint"]
                                </div>
                            </svg>
                        </div>
                    </div>
                </div>
            }
            <div class="grid-list">
                    @if (Model.Courses == null || Model.Courses.Count == 0)
                    {
                        @Html.Partial("NoContent")
                    }
                    else
                    {
                        @foreach (var course in Model.Courses)
                        {
                            <div class="grid-list__item">
                                @Html.Partial("CourseCard", course)
                            </div>
                        }
                    }
                </div>
            </div>
    </section>
</div>

TheExampleApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["ActivePage"] = "Home";
    ViewData["Title"] = "Home";
}


<div class="layout-centered">
    <vc:editorial-features sys="@Model.SystemProperties"></vc:editorial-features>
</div>

<div class="modules-container">
    @if (Model.IndexPage.ContentModules == null || Model.IndexPage.ContentModules.Count == 0)
    {
        @Html.Partial("NoContent")
    }
    else
    {
        @foreach (var module in Model.IndexPage.ContentModules)
        {
            @Html.Partial(module.GetType().Name, module)
        }
    }
</div>

TheExampleApp/Pages/_Layout.cshtml
@{
    Func<string, string> isActive = (s) => { return ViewData["ActivePage"]?.ToString() == s ? "active" : ""; };
    Func<string> getCustomParameters = () => {
        if (!Manager.IsUsingCustomCredentials)
        {
            return "";
        }

        return $"?space_id={Manager.Options.SpaceId}&preview_token={Manager.Options.PreviewApiKey}&delivery_token={Manager.Options.DeliveryApiKey}&api={(Manager.Options.UsePreviewApi ? "cpa" : "cda")}{(Context.Session.GetString("EditorialFeatures") == "Enabled" ? "&editorial_features=enabled" : "")}";
    };
    var rawTarget = Context.Features.Get<Microsoft.AspNetCore.Http.Features.IHttpRequestFeature>().RawTarget;
    if(rawTarget?.IndexOf("?") > 0)
    {
        rawTarget = rawTarget.Substring(0, rawTarget.IndexOf("?"));
    }
}

<!DOCTYPE html>
<html>
<head>
    <vc:meta-tags title="@ViewData["Title"]"></vc:meta-tags>
    <link rel="stylesheet" href="~/stylesheets/style.css" />
</head>
<body>
    <main class="main">
        <div class="main__header">
            <header class="header">
                <div class="header__upper-wrapper">
                    <div class="header__upper layout-centered">
                        <div class="header__upper-title">
                            <a id="about-this-modal-trigger" href="#" class="header__upper-link">
                                <svg class="header__upper-icon">
                                    <use xlink:href="/icons/icons.svg#info"></use>
                                </svg>
                                <span>@Localizer["whatIsThisApp"]</span>
                            </a>
                        </div>
                            <div class="header__upper-copy">
                                <a class="header__upper-link" target="_blank" rel="noopener" href="https://github.com/contentful/the-example-app.csharp">
                                    <svg class="header__upper-icon">
                                        <use xlink:href="/icons/icons.svg#github"></use>
                                    </svg>
                                    @Localizer["viewOnGithub"]
                                </a>
                            </div>
                            <div class="header__controls">
                                <vc:selected-api current-path="@rawTarget"></vc:selected-api>
                                <vc:locales></vc:locales>
                            </div>
                            <div class="header__upper-menu">
                            <a href="/settings" class="@isActive("Settings")">@Localizer["settingsLabel"]</a>
                        </div>
                </div>
            </div>
            <div class="header__lower-wrapper">
                <div class="header__lower layout-centered">
                    <div class="header__logo">
                        <a class="header__logo-link" href="/">
                            <img src="~/images/the-example-app-logo-dotnet.svg" alt="@Localizer["logoAlt"]" />
                        </a>
                    </div>
                    <nav class="header__navigation main-navigation">
                        <ul>
                            <li><a href="/" class="@isActive("Home")">@Localizer["homeLabel"]</a></li>
                            <li><a href="/courses" class="@isActive(null)">@Localizer["coursesLabel"]</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
    </div>
    <div class="main__content">
        @RenderBody()
    </div>
    <div class="main__footer">
        <div class="layout-centered">
            <footer class="footer">
                <div class="footer__upper">
                    <nav class="footer__navigation main-navigation">
                        <ul>
                            <li><a href="/" class="@isActive("Home")">@Localizer["homeLabel"]</a></li>
                            <li><a href="/courses" class="@isActive(null)">@Localizer["coursesLabel"]</a></li>
                        </ul>
                    </nav>
                    <div class="footer__apps"></div>
                </div>
                <div class="footer__lower">
                    <div class="footer__logo">
                        <a href="https://www.contentful.com/" target="_blank" rel="noopener"><img class="footer__disclaimer-logo" src="/images/contentful-logo.svg"></a>
                    </div>
                    <div class="footer__disclaimer">
                        <p class="footer__disclaimer-text">@Localizer["footerDisclaimer"] <a href="https://github.com/contentful/the-example-app.csharp" target="_blank" rel="noopener">@Localizer["viewOnGithub"]</a>.&nbsp;<a href="/imprint">@Localizer["imprintLabel"]</a>.&nbsp;<a href="https://www.contentful.com/contact/" target="_blank">@Localizer["contactUsLabel"]</a>.</p>
                    </div>
                    <div class="footer__social">
                        <p>
                            <a href="https://www.facebook.com/contentful/" target="_blank" rel="noopener"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/icons/icons.svg#facebook"></use></svg></a>
                            <a href="https://twitter.com/contentful" target="_blank" rel="noopener"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/icons/icons.svg#twitter"></use></svg></a>
                            <a href="https://github.com/contentful" target="_blank" rel="noopener"><svg class="header__upper-icon"><use xlink:href="/icons/icons.svg#github"></use></svg></a>
                        </p>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</main>

<section class="modal" id="about-this-modal">
    <div class="modal__overlay close"></div>
    <div class="modal__wrapper">
        <h1 class="modal__title">@Localizer["modalTitleDotnet"]</h1>
        <div class="modal__content">
            <p>@Localizer["modalIntroDotnet"]&nbsp;<a href="https://github.com/contentful/the-example-app.csharp" target="_blank" rel="noopener">Github</a>.</p>
            <p>@Localizer["modalSpaceIntro"]&nbsp;<a href="https://github.com/contentful/content-models/blob/master/the-example-app/README.md " target="_blank" rel="noopener">@Localizer["modalSpaceLinkLabel"]</a>.</p>
            <p>@Localizer["modalPlatforms"]</p>
            <ul>
                <li>
                    <img src="/images/nodejs-icon.svg"><br />
                    <a href="https://the-example-app-nodejs.contentful.com/@getCustomParameters()" rel="noopener" target="_blank">@Localizer["hostedLabel"]</a> <br />
                    <a href="https://github.com/contentful/the-example-app.nodejs" rel="noopener" target="_blank">GitHub</a>
                </li>
                <li>
                    <img src="/images/dotnet.svg"><br />
                    <a href="https://the-example-app-csharp.contentful.com/@getCustomParameters()" rel="noopener" target="_blank">@Localizer["hostedLabel"]</a> <br />
                    <a href="https://github.com/contentful/the-example-app.csharp" rel="noopener" target="_blank">GitHub</a>
                </li>
                <li>
                    <img src="/images/ruby.svg"><br />
                    <a href="https://the-example-app-rb.contentful.com/@getCustomParameters()" rel="noopener" target="_blank">@Localizer["hostedLabel"]</a> <br />
                    <a href="https://github.com/contentful/the-example-app.rb" rel="noopener" target="_blank">GitHub</a>
                </li>
                <li>
                    <img src="/images/php.svg"><br />
                    <a href="https://the-example-app-php.contentful.com/@getCustomParameters()" rel="noopener" target="_blank">@Localizer["hostedLabel"]</a> <br />
                    <a href="https://github.com/contentful/the-example-app.php" rel="noopener" target="_blank">GitHub</a>
                </li>
                <li>
                    <img src="/images/python.svg"><br />
                    <a href="https://the-example-app-py.contentful.com/@getCustomParameters()" rel="noopener" target="_blank">@Localizer["hostedLabel"]</a> <br />
                    <a href="https://github.com/contentful/the-example-app.py" rel="noopener" target="_blank">GitHub</a>
                </li>
                <li>
                    <img src="/images/java.svg"><br />
                    <a href="https://the-example-app-java.contentful.com/@getCustomParameters()" rel="noopener" target="_blank">@Localizer["hostedLabel"]</a> <br />
                    <a href="https://github.com/contentful/the-example-app.java" rel="noopener" target="_blank">GitHub</a>
                </li>
                <li>
                    <img src="/images/swift.svg"><br />
                    <a href="https://itunes.apple.com/app/contentful-reference/id1333721890" rel="noopener" target="_blank">@Localizer["hostedLabel"]</a> <br />
                    <a href="https://github.com/contentful/the-example-app.swift" rel="noopener" target="_blank">GitHub</a>
                </li>
                <li>
                    <img src="/images/android-icon.svg"><br />
                    <a href="https://play.google.com/store/apps/details?id=com.contentful.tea.kotlin" rel="noopener" target="_blank">@Localizer["hostedLabel"]</a> <br />
                    <a href="https://github.com/contentful/the-example-app.kotlin" rel="noopener" target="_blank">GitHub</a>
                </li>
            </ul>
        </div>
        <div class="modal__cta-wrapper">
            <a class="modal__cta close" href="#">@Localizer["modalCTALabel"]</a>
        </div>
        <div class="modal__close-wrapper">
            <a class="modal__close-button close" href="#">
                <svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/icons/icons.svg#cross"></use></svg>
            </a>
        </div>
    </div>
</section>

<script src="~/scripts/index.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
<environment include="Heroku">
    @Html.Partial("Analytics")
</environment>
</body>
</html>