TheExampleApp/ViewComponents/EntryStateViewComponent.cs
using Contentful.Core;
using Contentful.Core.Configuration;
using Contentful.Core.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using TheExampleApp.Configuration;

namespace TheExampleApp.ViewComponents
{
    /// <summary>
    /// View component handling the state of an entry.
    /// </summary>
    public class EntryStateViewComponent : ViewComponent
    {
        private readonly HttpClient _httpClient;
        private readonly ContentfulOptions _options;

        /// <summary>
        /// Instantiate the view component.
        /// </summary>
        /// <param name="httpClient">The httpclient to use for a separate call to the Contentful API.</param>
        /// <param name="optionsManager">The class that manages the Contentful configuration for the application.</param>
        public EntryStateViewComponent(HttpClient httpClient, IContentfulOptionsManager optionsManager)
        {
            _httpClient = httpClient;
            _options = optionsManager.Options;
        }

        /// <summary>
        /// Invokes the view component and returns the result.
        /// </summary>
        /// <param name="sys">They system properties of the entry to display status for.</param>
        /// <returns>The view.</returns>
        public async Task<IViewComponentResult> InvokeAsync(IEnumerable<SystemProperties> sys)
        {
            // Create a new client with preview set to false to always get the entry from the delivery API.
            var client = new ContentfulClient(_httpClient, _options.DeliveryApiKey, _options.PreviewApiKey, _options.SpaceId, false);
            IEnumerable<EntryStateModel> entries = null;
            var model = new EntryStateModel();
            try
            {
                // Try getting the entry by the specified Id. If it throws or returns null the entry is not published.
                entries = await client.GetEntries<EntryStateModel>($"?sys.id[in]={string.Join(",", sys.Select(c => c.Id))}");
            }
            catch { }

            if(entries == null || (entries.Any() == false || sys.Select(c => c.Id).Except(entries.Select(e => e.Sys.Id)).Any()))
            {
                // One of the entries are not published, thus it is in draft mode.
                model.Draft = true;
            }

            if (entries != null && AnySystemPropertiesNotMatching(entries.Select(c => c.Sys),sys))
            {
                // The entry is published but the UpdatedAt dates do not match, thus it must have pending changes.
                model.PendingChanges = true;
            }

            return View(model);

            bool AnySystemPropertiesNotMatching(IEnumerable<SystemProperties> published, IEnumerable<SystemProperties> preview)
            {
                foreach (var publishedEntry in published)
                {
                    var previewEntry = preview.FirstOrDefault(c => c.Id == publishedEntry.Id);
                    if(TrimMilliseconds(publishedEntry.UpdatedAt) != TrimMilliseconds(previewEntry?.UpdatedAt))
                    {
                        // At least one of the entries have UpdatedAt that does not match, thus it has pending changes.
                        return true;
                    }
                }
                
                return false;
            }

            DateTime? TrimMilliseconds(DateTime? dateTime)
            {
                if (!dateTime.HasValue)
                {
                    return dateTime;
                }

                return new DateTime(dateTime.Value.Year, dateTime.Value.Month, dateTime.Value.Day, dateTime.Value.Hour, dateTime.Value.Minute, dateTime.Value.Second, 0);
            }
        }
    }

    /// <summary>
    /// Model for the <see cref="EntryStateViewComponent"/> view.
    /// </summary>
    public class EntryStateModel
    {
        /// <summary>
        /// The system properties of the entry to display status for.
        /// </summary>
        public SystemProperties Sys { get; set; }

        /// <summary>
        /// Whether the entry is a draft or not.
        /// </summary>
        public bool Draft { get; set; }

        /// <summary>
        /// Whether the entry has pending changes or not.
        /// </summary>
        public bool PendingChanges { get; set; }
    }
}

TheExampleApp/Views/Shared/Analytics.cshtml
@inject TheExampleApp.Configuration.IContentfulOptionsManager manager
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-109296848-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-40725207-13');
</script>

<script async>
    ; (function (p, l, o, w, i, n, g) {
        if (!p[i]) {
            p.GlobalSnowplowNamespace = p.GlobalSnowplowNamespace || [];
            p.GlobalSnowplowNamespace.push(i); p[i] = function () {
                (p[i].q = p[i].q || []).push(arguments)
            }; p[i].q = p[i].q || []; n = l.createElement(o); g = l.getElementsByTagName(o)[0]; n.async = 1;
            n.src = w; g.parentNode.insertBefore(n, g)
        }
    }(window, document, "script", "//d1fc8wv8zag5ca.cloudfront.net/2.8.2/sp.js", "snowplow"));

    snowplow('newTracker', 'defaultTracker', 'col.contentful.com', {
        appId: 'the-example-app',
        platform: 'web',
        respectDoNotTrack: true,
        bufferSize: 1,
        cookieDomain: window.location.host,
        contexts: {
            webPage: true,
            gaCookies: true,
            geolocation: false
        }
    });

    snowplow('trackPageView');

    snowplow('enableLinkClickTracking')

    snowplow('trackSelfDescribingEvent', {
        schema: 'iglu:com.contentful/app_the_example_app_open/jsonschema/1-0-0',
        data: {
            space_id: '@manager.Options.SpaceId',
            sdk_language_used: 'csharp',
            app_framework: '.net'
        }
    });
</script>

TheExampleApp/Views/Shared/Breadcrumbs.cshtml
@{
    var crumbs = Context.Items["breadcrumbs"] as List<TheExampleApp.Configuration.Breadcrumb>;
}

@if (crumbs != null)
{
        <nav class="breadcrumb">
            <ul>
                @foreach (var crumb in crumbs)
                {
                    <li><a href="@crumb.Path">@crumb.Label</a></li>
                }
            </ul>
        </nav>
}

TheExampleApp/Views/Shared/CourseCard.cshtml
@model Course

<div class="course-card">
    <div class="course-card__categories">
        @if (Model.Categories != null && Model.Categories.Any())
        {
            foreach (var category in Model.Categories)
            {
                <div class="course-card__category"><a class="course-card__category-link" href="/courses/categories/@category.Slug">@category.Title</a></div>
            }
        }
    </div>
    <h2 class="course-card__title"><a href="/courses/@Model.Slug">@Model.Title</a> <vc:entry-state sys="new[] { Model.Sys }"></vc:entry-state></h2>
    
    <p class="course-card__description">
        @Model.ShortDescription
    </p>
    <div class="course-card__link-wrapper">
        <a class="course-card__link" href="/courses/@Model.Slug">@Localizer["viewCourseLabel"]</a>
    </div>
</div>

TheExampleApp/Views/Shared/LayoutCopy.cshtml
@model LayoutCopy

@{ var visualStyle = Model.VisualStyle == "Emphasized" ? "--emphasized" : ""; }
<div class="module @("module-copy"+visualStyle)">
    <div class="@("module-copy__wrapper"+visualStyle)">
        <div class="@("module-copy__first" + visualStyle)">
            @if (!string.IsNullOrEmpty(Model.Headline))
            {
                <h1 class="@("module-copy__headline" + visualStyle)">@Model.Headline </h1>
            }
            <div class="@("module-copy__copy" + visualStyle)"><markdown content="@Model.Copy" /></div>
        </div>
        <div class="@("module-copy__second" + visualStyle)">
            @if (!string.IsNullOrEmpty(Model.CtaLink) && !string.IsNullOrEmpty(Model.CtaTitle))
            {
                <a class="cta @("module-copy__cta" + visualStyle)" href="@Model.CtaLink">@Model.CtaTitle</a>
            }
        </div>
    </div>
</div>

TheExampleApp/Views/Shared/LayoutHeroImage.cshtml
@model LayoutHeroImage

@if (Model == null || Model.BackgroundImage == null)
{
    <div class="module module-hero-image">
        <h3>@Localizer["imageErrorTitle"]</h3>
    </div>
}
else
{
    <div class="module module-hero-image">
        <div class="module-hero-image__wrapper">
            <div class="module-hero-image__headline-wrapper">
                <h2 class="module-hero-image__headline">@Model.Headline</h2>
            </div>
            <contentful-image class="module-hero-image__image" url="@Model.BackgroundImage.File.Url" />
        </div>
    </div>
}

TheExampleApp/Views/Shared/LayoutHighlightedCourse.cshtml
@model LayoutHighlightedCourse
@if (Model.Course == null)
{
<div class="module module-highlighted-course">
    <div class="module-highlighted-course__wrapper" >
        <div class="module-highlighted-course__overlay"></div>
        <div class="module-highlighted-course__content">
          
            <h2 class="module-highlighted-course__title">
                <a href="#">@Localizer["errorHighlightedCourse"]</a>
            </h2>
            <div class="module-highlighted-course__description-wrapper">
                <p></p>
            </div>
        </div>
    </div>
</div>
}
else
{
    <div class="module module-highlighted-course">
        <div class="module-highlighted-course__wrapper" style="background-image:url(@Model?.Course?.Image?.File?.Url);">
            <div class="module-highlighted-course__overlay"></div>
            <div class="module-highlighted-course__content">
                @if (Model.Course?.Categories != null && Model.Course.Categories.Any())
                {
                    <div class="module-highlighted-course__categories">
                        @foreach (var category in Model.Course.Categories)
                        {
                            <a class="module-highlighted-course__category" href="/courses/categories/@category.Slug">@category.Title</a>
                        }
                    </div>
                }
                <h2 class="module-highlighted-course__title">
                    <a href="/courses/@Model.Course?.Slug">@Model.Course?.Title</a>
                </h2>
                <div class="module-highlighted-course__description-wrapper">
                    <p markdown>@Model.Course?.ShortDescription</p>
                </div>
                <div class="module-highlighted-course__link-wrapper">
                    <a class="module-highlighted-course__link" href="/courses/@Model.Course?.Slug">@Localizer["viewCourseLabel"]</a>
                </div>
            </div>
        </div>
    </div>
}

TheExampleApp/Views/Shared/LessonCodeSnippets.cshtml
@model LessonCodeSnippets

<div class="lesson-module lesson-module-code">

    <div class="lesson-module-code__header">
        @if (!string.IsNullOrEmpty(Model.Curl))
        {
            <a class="lesson-module-code__trigger" data-target="curl">cURL</a>
        }
        @if (!string.IsNullOrEmpty(Model.DotNet))
        {
            <a class="lesson-module-code__trigger lesson-module-code__trigger--active" data-target="dotnet">.NET</a>
        }
        @if (!string.IsNullOrEmpty(Model.Javascript))
        {
            <a class="lesson-module-code__trigger" data-target="javascript">JavaScript</a>
        }
        @if (!string.IsNullOrEmpty(Model.Java))
        {
            <a class="lesson-module-code__trigger" data-target="java">Java</a>
        }
        @if (!string.IsNullOrEmpty(Model.JavaAndroid))
        {
            <a class="lesson-module-code__trigger" data-target="android">Android</a>
        }
        @if (!string.IsNullOrEmpty(Model.Php))
        {
            <a class="lesson-module-code__trigger" data-target="php">PHP</a>
        }
        @if (!string.IsNullOrEmpty(Model.Python))
        {
            <a class="lesson-module-code__trigger" data-target="python">Python</a>
        }
        @if (!string.IsNullOrEmpty(Model.Ruby))
        {
            <a class="lesson-module-code__trigger" data-target="ruby">Ruby</a>
        }
        @if (!string.IsNullOrEmpty(Model.Swift))
        {
            <a class="lesson-module-code__trigger" data-target="swift">Swift</a>
        }
    </div>
    <div class="lesson-module-code__code-area">
        @if (!string.IsNullOrEmpty(Model.Curl))
        {
            <div class="lesson-module-code__code" id="curl">
                <pre><code class="shell">@Model.Curl</code></pre>
            </div>
        }
        @if (!string.IsNullOrEmpty(Model.DotNet))
        {
            <div class="lesson-module-code__code lesson-module-code__code--active" id="dotnet">
                <pre><code class="csharp">@Model.DotNet</code></pre>
            </div>
        }
        @if (!string.IsNullOrEmpty(Model.Javascript))
        {
            <div class="lesson-module-code__code" id="javascript">
                <pre><code class="javascript">@Model.Javascript</code></pre>
            </div>
        }
        @if (!string.IsNullOrEmpty(Model.Java))
        {
            <div class="lesson-module-code__code" id="java">
                <pre><code class="java">@Model.Java</code></pre>
            </div>
        }
        @if (!string.IsNullOrEmpty(Model.JavaAndroid))
        {
            <div class="lesson-module-code__code" id="android">
                <pre><code class="java">@Model.JavaAndroid</code></pre>
            </div>
        }
        @if (!string.IsNullOrEmpty(Model.Php))
        {
            <div class="lesson-module-code__code" id="php">
                <pre><code class="php">@Model.Php</code></pre>
            </div>
        }
        @if (!string.IsNullOrEmpty(Model.Python))
        {
            <div class="lesson-module-code__code" id="python">
                <pre><code class="python">@Model.Python</code></pre>
            </div>
        }
        @if (!string.IsNullOrEmpty(Model.Ruby))
        {
            <div class="lesson-module-code__code" id="ruby">
                <pre><code class="ruby">@Model.Ruby</code></pre>
            </div>
        }
        @if (!string.IsNullOrEmpty(Model.Swift))
        {
            <div class="lesson-module-code__code" id="swift">
                <pre><code class="swift">@Model.Swift</code></pre>
            </div>
        }
    </div>
</div>

TheExampleApp/Views/Shared/LessonCopy.cshtml
@model LessonCopy

<div class="lesson-module lesson-module-copy">
    <div class="lesson-module-copy__copy">
        <markdown content="@Model.Copy"></markdown>
    </div>
</div>

TheExampleApp/Views/Shared/LessonImage.cshtml
@model LessonImage

<div class="lesson-module lesson-module-image">
    @if (Model.Image != null && Model.Image.File != null && Model.Image.File.Url != null)
    {
        <figure class="lesson-module-image__figure">
            <contentful-image class="lesson-module-image__image" url="@Model.Image?.File?.Url" />
            @if (!string.IsNullOrEmpty(Model.Caption))
            {
                <figcaption class="lesson-module-image__caption">@Model.Caption</figcaption>
            }
        </figure>
    }
    else
    {
        <h3>@Localizer["imageErrorTitle"]</h3>
    }
</div>

TheExampleApp/Views/Shared/NoContent.cshtml
<div class="module">
    <h2>@Localizer["noContentLabel"]</h2>

    <h3>@Localizer["hintsLabel"]</h3>
    <ul>
        <li>@Localizer["notFoundErrorHint"] </li>
        <li>@Localizer["draftOrPublishedErrorHint"]</li>
    </ul>
</div>

TheExampleApp/Views/Shared/TableOfContents.cshtml
@model Course
@{ 
    Func<string, string> isVisited = (s) => { return (ViewData["VisitedLessons"] as List<string>).Contains(s) ? "visited" : ""; };
}
@if (Model != null)
{
<section class="layout-sidebar__sidebar">
    <div class="layout-sidebar__sidebar-header">
        <h2 class="layout-sidebar__sidebar-title">@Localizer["tableOfContentsLabel"]</h2>
    </div>
    <div class="layout-sidebar__sidebar-content">
        <div class="table-of-contents">
            <ul class="table-of-contents__list">
                <li class="table-of-contents__item">
                    <a class="table-of-contents__link @(ViewData["slug"] == null ? "active" : "") @isVisited(Model.Sys.Id)" href="/courses/@Model.Slug">@Localizer["courseOverviewLabel"]</a>
                </li>
                @if (Model.Lessons != null && Model.Lessons.Any())
                {
                    @foreach (var lesson in Model.Lessons)
                    {
                        <li class="table-of-contents__item">
                            <a class="table-of-contents__link @(ViewData["slug"]?.ToString() == lesson.Slug ? "active" : "") @isVisited(lesson.Sys.Id)" href="/courses/@Model.Slug/lessons/@lesson.Slug">@lesson.Title</a>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
</section>
}